/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2CQVL2bugAh
 */


export function basics() {
  return (
    <div className="max-w-3xl mx-auto my-8 p-6 border rounded-md">
      <h1 className="text-2xl font-semibold mb-6">Course landing page</h1>
      <p className="mb-4">
        Your course landing page is crucial to your success on Udemy. If it's done right, it can also help you gain
        visibility in search engines like Google. As you complete this section, think about creating a compelling Course
        Landing Page that demonstrates why someone would want to enroll in your course. Learn more about
        <a className="text-blue-600" href="#">
          creating your course landing page
        </a>{" "}
        and{" "}
        <a className="text-blue-600" href="#">
          course title standards
        </a>
        .{"\n      "}
      </p>
      <div className="mb-4">
        <label className="block text-sm font-medium mb-1" htmlFor="course-title">
          Course title
        </label>
        <input className="w-full border px-2 py-1" id="course-title" placeholder="Sample" type="text" />
        <p className="text-xs mt-1">
          Your title should be a mix of attention-grabbing, informative, and optimized for search
        </p>
      </div>
      <div className="mb-4">
        <label className="block text-sm font-medium mb-1" htmlFor="course-subtitle">
          Course subtitle
        </label>
        <input
          className="w-full border px-2 py-1"
          id="course-subtitle"
          placeholder="Insert your course subtitle."
          type="text"
        />
        <p className="text-xs mt-1">
          Use 1-2 related keywords, and mention 3-4 of the most important areas that you'll cover during your course.
        </p>
      </div>
      <div className="mb-4">
        <label className="block text-sm font-medium mb-1" htmlFor="course-description">
          Course description
        </label>
        <textarea
          className="w-full border px-2 py-1"
          id="course-description"
          placeholder="Insert your course description."
          rows="4"
        />
        <p className="text-xs mt-1">Description should have minimum 200 words.</p>
      </div>
      <div className="mb-4 grid grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium mb-1" htmlFor="language">
            Basic info
          </label>
          <select className="w-full border px-2 py-1" id="language">
            <option>English (US)</option>
          </select>
        </div>
        <div>
          <label className="sr-only" htmlFor="level">
            Select Level
          </label>
          <select className="w-full border px-2 py-1" id="level">
            <option hidden>-- Select Level --</option>
          </select>
        </div>
        <div>
          <label className="sr-only" htmlFor="category">
            Select Category
          </label>
          <select className="w-full border px-2 py-1" id="category">
            <option>IT & Software</option>
          </select>
        </div>
        <div>
          <label className="sr-only" htmlFor="subcategory">
            Select Subcategory
          </label>
          <select className="w-full border px-2 py-1" id="subcategory">
            <option hidden>-- Select Subcategory --</option>
          </select>
        </div>
      </div>
      <div className="mb-4">
        <label className="block text-sm font-medium mb-1" htmlFor="primary-topic">
          What is primarily taught in your course?
        </label>
        <input
          className="w-full border px-2 py-1"
          id="primary-topic"
          placeholder="e.g. Landscape Photography"
          type="text"
        />
      </div>
      <div className="mb-4">
        <label className="block text-sm font-medium mb-1">Course image</label>
        <div className="flex justify-between items-center p-4 border-dashed border-2 rounded-md mb-2">
          <span className="text-sm">
            Upload your course image here. It must meet our{" "}
            <a className="text-blue-600" href="#">
              course image quality standards
            </a>{" "}
            to be accepted. Important guidelines: 750x422 pixels; .jpg, .jpeg, .gif, or .png; not text on the image.
          </span>
          <button className="bg-blue-600 text-white px-3 py-1 rounded">Upload File</button>
        </div>
      </div>
      <div className="mb-4">
        <label className="block text-sm font-medium mb-1">Promotional video</label>
        <div className="flex justify-between items-center p-4 border-dashed border-2 rounded-md">
          <span className="text-sm">
            Your promo video is a quick and compelling way for students to preview what they'll learn in your course.
            Students considering your course are more likely to enroll if your promo video is well-made. Learn how to
            make your promo video{" "}
            <a className="text-blue-600" href="#">
              awesome
            </a>
            .
          </span>
          <button className="bg-blue-600 text-white px-3 py-1 rounded">Upload File</button>
        </div>
      </div>
    </div>
  )
}
