/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nYXu0hlvDuh
 */
import { JSX, SVGProps } from "react";

export function Lecture(props: any) {
  return (
    <div className="max-w-4xl mx-auto p-6 bg-white rounded-lg border-2 border-black my-4">
      <div className="flex justify-between items-start border-b pb-2">
        <div className="flex items-center space-x-2">
          <h2 className="text-lg font-semibold">
            Lecture {props.index + 1}: {props.lecture.name}
          </h2>
        </div>
      </div>
      <div className="mt-4 flex justify-between items-center">
        <div className="flex space-x-4">
          <img
            alt="Video thumbnail"
            className="h-15 w-20 bg-gray-200"
            height="60"
            src="https://images.pexels.com/photos/1037992/pexels-photo-1037992.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
            style={{
              aspectRatio: "80/60",
              objectFit: "cover",
            }}
            width="80"
          />
          <div>
            <p className="font-medium">sample.mp4</p>
            <p className="text-sm text-gray-500">00:19</p>
          </div>
        </div>
      </div>
    </div>
  );
}
