/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MLomark9JZf
 */
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Textarea } from "../ui/textarea";
import { useRef, useState } from "react";

export function NewLectureForm(props: any) {
  const videoInputRef = useRef<any>(null);
  const [title, setTitle] = useState<any>();
  const [description, setDescription] = useState<any>();
  const [video, setVideo] = useState<any>(null);

  function uploadFile(event: any) {
    let file = event.target.files[0];
    console.log(file);

    if (file) {
      // let data = new FormData();
      // data.append("file", file);
      // axios.post('/files', data)...
      setVideo(file);
    }
  }

  const UploadLecture = (e: any) => {
    e.preventDefault();
    console.log("Title:", title);
    console.log("Description:", description);
    console.log("Video:", video);
    props.setShowNewLectureForm(false);
  };

  return (
    <form onSubmit={UploadLecture}>
      <div className="max-w-4xl mx-auto p-4 border-2 border-black  rounded-md dark:border-gray-800">
        <div className="flex flex-col space-y-4">
          <div className="flex items-center space-x-2">
            <label className="font-medium w-1/6" htmlFor="new-lecture">
              New Lecture:
            </label>
            <Input
              className="flex-1"
              id="new-lecture"
              placeholder="Enter a Title"
              autoComplete="off"
              value={title}
              onChange={(e) => {
                setTitle(e.target.value);
              }}
            />
          </div>
          <div className="flex items-top space-x-2">
            <label className="font-medium w-1/6" htmlFor="lecture-desciption">
              Description :
            </label>
            <Textarea
              className="flex-1"
              id="lecture-desciption"
              placeholder="Enter a Description"
              value={description}
              onChange={(e) => {
                setDescription(e.target.value);
              }}
            />
          </div>
          <div className="flex items-top space-x-2">
            <label className="font-medium w-1/6" htmlFor="lecture-desciption">
              Upload Video :
            </label>
            <Button
              className="ml-2 border border-gray hover:bg-gray-300"
              onClick={() => {
                console.log(props.showNewLectureForm);
                videoInputRef.current && videoInputRef.current.click();
              }}
              type="button"
            >
              Upload
            </Button>

            {video && <p className="pt-2">{video.name}</p>}
            <input
              type="file"
              accept="video/*"
              style={{ display: "none" }}
              ref={videoInputRef}
              onChange={uploadFile}
            ></input>
          </div>
          <div className="flex justify-end">
            <Button
              type="button"
              className="ml-2 border-2 border-black hover:bg-gray-300"
              onClick={() => {
                props.setShowNewLectureForm(false);
              }}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              className="ml-2 border-2 border-black hover:bg-gray-300"
            >
              Add Lecture
            </Button>
          </div>
        </div>
      </div>
    </form>
  );
}
