/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qDGWWxnOuI7
 */
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useState } from "react";

export function NewSectionForm(_props: any) {
  const [sectionName, setSectioName] = useState("");
  
  
  return (
    <div className="max-w-4xl mx-auto my-8 p-6 border border-gray-200 rounded-md space-y-6 dark:border-gray-800">
      <div>
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">New Section:</h2>
        </div>
        <div className="mt-4 grid grid-cols-1 gap-y-4">
          <Input placeholder="Enter a Title" value={sectionName} onChange={(e) => {
            setSectioName(e.target.value);
          }} />
        </div>
        <div className="flex justify-end space-x-4 mt-4">
          <Button className="ml-2 border-2 border-black hover:bg-gray-300"
            onClick={() => {
              _props.setShowForm(false);
            }}
          >
            Cancel
          </Button>
          <Button className="ml-2 border-2 border-black hover:bg-gray-300"
            onClick={() => {
              if (sectionName)
              {
                console.log("Section created with section name:", sectionName);
                _props.setShowForm(false);
              }
            }}
          >
            Add Section
          </Button>
        </div>
      </div>
    </div>
  );
}
