/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UW8Hpd9Y47t
 */
import { Button } from "@/components/ui/button";
import { Lecture } from "./lecture";
import { useState } from "react";
import { NewLectureForm } from "./new-lecture-form";

export function Section(props: any) {
  const [showNewLectureForm, setShowNewLectureForm] = useState(false);
  return (
    <div className="max-w-4xl mx-auto my-8 p-6 border border-gray-200 rounded-md dark:border-gray-800">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-semibold">
          Section {props.index + 1}: {props?.section?.name}
        </h2>
      </div>
      <div className="border-t pt-4">
        <div>
          {props?.section?.lectures.map((lecture: any, i: any) => {
            return <Lecture lecture={lecture} key={i} index={i} />;
          })}
        </div>
      </div>
      {!showNewLectureForm && (
        <Button
          className="border-2 border-black hover:bg-gray-300"
          onClick={() => {
            setShowNewLectureForm(true);
          }}
        >
          + Curriculum item
        </Button>
      )}
      {showNewLectureForm && (
        <NewLectureForm setShowNewLectureForm={setShowNewLectureForm} showNewLectureForm={showNewLectureForm} />
      )}
    </div>
  );
}
