/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cIM9HFZK8fC
 */
import { Button } from "@/components/ui/button"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { JSX, SVGProps } from "react"

export function CourseCreationForm() {
  return (
    <div className="flex h-screen bg-gray-100">
      <aside className="w-64 px-4 py-8 bg-white border-r">
        <nav className="space-y-1">
          <p className="text-xs font-semibold text-gray-500 uppercase">Plan your course</p>
          <a className="flex items-center px-2 py-1 text-gray-600 rounded-md hover:bg-gray-50" href="#">
            <CircleIcon className="w-4 h-4 mr-2 text-gray-400" />
            Intended learners
          </a>
          <a className="flex items-center px-2 py-1 text-gray-600 rounded-md hover:bg-gray-50" href="#">
            <CheckCircleIcon className="w-4 h-4 mr-2 text-green-500" />
            Course structure
          </a>
          <a className="flex items-center px-2 py-1 text-gray-600 rounded-md hover:bg-gray-50" href="#">
            <CheckCircleIcon className="w-4 h-4 mr-2 text-green-500" />
            Setup & test video
          </a>
          <p className="mt-4 text-xs font-semibold text-gray-500 uppercase">Create your content</p>
          <a className="flex items-center px-2 py-1 text-gray-600 rounded-md hover:bg-gray-50" href="#">
            <CheckCircleIcon className="w-4 h-4 mr-2 text-green-500" />
            Film & edit
          </a>
          <a className="flex items-center px-2 py-1 text-purple-600 rounded-md bg-purple-100" href="#">
            <SettingsIcon className="w-4 h-4 mr-2" />
            Curriculum
          </a>
          <a className="flex items-center px-2 py-1 text-gray-600 rounded-md hover:bg-gray-50" href="#">
            <CircleIcon className="w-4 h-4 mr-2 text-gray-400" />
            Captions (optional)
          </a>
          <a className="flex items-center px-2 py-1 text-gray-600 rounded-md hover-bg-gray-50" href="#">
            <CheckCircleIcon className="w-4 h-4 mr-2 text-green-500" />
            Accessibility (optional)
          </a>
          <p className="mt-4 text-xs font-semibold text-gray-500 uppercase">Publish your course</p>
          <a className="flex items-center px-2 py-1 text-gray-600 rounded-md hover-bg-gray-50" href="#">
            <CircleIcon className="w-4 h-4 mr-2 text-gray-400" />
            Course landing page
          </a>
          <a className="flex items-center px-2 py-1 text-gray-600 rounded-md hover-bg-gray-50" href="#">
            <CircleIcon className="w-4 h-4 mr-2 text-gray-400" />
            Pricing
          </a>
          <a className="flex items-center px-2 py-1 text-gray-600 rounded-md hover-bg-gray-50" href="#">
            <CheckCircleIcon className="w-4 h-4 mr-2 text-green-500" />
            Promotions
          </a>
          <a className="flex items-center px-2 py-1 text-gray-600 rounded-md hover-bg-gray-50" href="#">
            <CircleIcon className="w-4 h-4 mr-2 text-gray-400" />
            Course messages
          </a>
        </nav>
        <Button className="w-full mt-6 bg-purple-600 text-white">Submit for Review</Button>
      </aside>
      <main className="flex-1 px-8 py-8">
        <header className="flex justify-between items-center">
          <h1 className="text-2xl font-semibold">Teaching Blockchain</h1>
          <div className="flex items-center space-x-4">
            <span className="px-2 py-1 text-xs font-semibold text-purple-600 bg-purple-100 rounded-full">DRAFT</span>
            <Button variant="outline">Preview</Button>
            <CogIcon className="w-6 h-6 text-gray-600" />
          </div>
        </header>
        <section className="mt-8">
          <div className="grid grid-cols-3 gap-8">
            <div className="col-span-3 p-6 bg-white rounded-md shadow">
              <h2 className="text-lg font-semibold">Curriculum</h2>
              <p className="mt-2 text-sm text-gray-600">
                Start putting together your course by creating sections, lectures and practice (quizzes, coding
                exercises and assignments). Use your course outline to structure your content and label your sections
                and lectures clearly. If you’re intending to offer your course for free, the total length of video
                content must be less than 2 hours.
              </p>
              <div className="mt-4">
                <div className="flex items-center justify-between px-4 py-2 bg-gray-50 rounded-md">
                  <span className="text-sm font-medium">Section 1: Introduction</span>
                  <Select>
                    <SelectTrigger id="section1">
                      <SelectValue placeholder="Content" />
                    </SelectTrigger>
                    <SelectContent position="popper">
                      <SelectItem value="lecture">Lecture</SelectItem>
                      <SelectItem value="quiz">Quiz</SelectItem>
                      <SelectItem value="assignment">Assignment</SelectItem>
                    </SelectContent>
                  </Select>
                  <Button className="ml-2">+ Section</Button>
                </div>
                <div className="flex items-center justify-between px-4 py-2 mt-2 bg-white rounded-md border">
                  <span className="text-sm font-medium ml-8">Lecture 1: Introduction</span>
                  <Select>
                    <SelectTrigger id="lecture1">
                      <SelectValue placeholder="Content" />
                    </SelectTrigger>
                    <SelectContent position="popper">
                      <SelectItem value="video">Video</SelectItem>
                      <SelectItem value="audio">Audio</SelectItem>
                      <SelectItem value="text">Text</SelectItem>
                    </SelectContent>
                  </Select>
                  <Button className="ml-2">+ Curriculum item</Button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}


function CircleIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
    </svg>
  )
}


function CheckCircleIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>
  )
}


function SettingsIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function CogIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20a8 8 0 1 0 0-16 8 8 0 0 0 0 16Z" />
      <path d="M12 14a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z" />
      <path d="M12 2v2" />
      <path d="M12 22v-2" />
      <path d="m17 20.66-1-1.73" />
      <path d="M11 10.27 7 3.34" />
      <path d="m20.66 17-1.73-1" />
      <path d="m3.34 7 1.73 1" />
      <path d="M14 12h8" />
      <path d="M2 12h2" />
      <path d="m20.66 7-1.73 1" />
      <path d="m3.34 17 1.73-1" />
      <path d="m17 3.34-1 1.73" />
      <path d="m11 13.73-4 6.93" />
    </svg>
  )
}
